// All user-visible Focus Session text lives here so it can move to the shared i18n
// dictionaries in one step later, without touching shared files during the sprint.
export const focusCopy = {
  title: "Focus Session",
  subtitle: "Timed work with automatic breaks. opencode checks in if you go quiet.",
  timing: "Timing",
  presetCustom: "Custom",
  workMinutes: "Work (min)",
  breakMinutes: "Break (min)",
  start: "Start session",
  pause: "Pause",
  resume: "Resume",
  end: "End session",
  working: "Focus time",
  onBreak: "Break time",
  paused: "Paused",
  round: (round: number) => `Round ${round}`,
  lockedNotice: "Focus session in progress. The rest of opencode is locked until your break.",
  unlockedNotice: "Unlocked so you can read the agent's answer. The timer is still running.",
  workComplete: "Work round complete. Enjoy your break!",
  breakEnded: "Break's over. Start another round?",
  anotherRound: "Start another round",
  done: "Done",
  status: {
    active: "Focused",
    idle: "Need help?",
    unresponsive: "No response",
    neutral: "Not tracking",
  },
  checkIn: "Need help?",
  checkInHint: "You've been quiet for a couple of minutes.",
  yes: "Yes, help me",
  no: "No, I'm fine",
  helpSending: "Asking the agent…",
  helpNoProject: "Add a project to ask the agent for help.",
  helpFailed: "Couldn't reach the agent. Try again.",
  history: (sessions: number, minutes: number) => `${sessions} sessions · ${minutes} focus minutes`,
}
